apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: wordpress-prod-ib
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://ibombel.jfrog.io/artifactory/wordpress-helm/'
    chart: wordpress-ib
    targetRevision: 0.0.7
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
