apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: wordpress-prod-ib
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://ibombel.jfrog.io/artifactory/api/helm/wordpress-helm'
    chart: wordpress-ib
    targetRevision: 0.*
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wp-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
